In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report, roc_auc_score
from imblearn.over_sampling import SMOTE

In [ ]:
credit_card_data = pd.read_csv('/content/creditcard.csv', sep=',')

In [ ]:
credit_card_data.head()

   Time        V1        V2        V3  ...       V27       V28  Amount  Class
0     0 -1.359807 -0.072781  2.536347  ...  0.133558 -0.021053  149.62    0.0
1     0  1.191857  0.266151  0.166480  ... -0.008983  0.014724    2.69    0.0
2     1 -1.358354 -1.340163  1.773209  ... -0.055353 -0.059752  378.66    0.0
3     1 -0.966272 -0.185226  1.792993  ...  0.062723  0.061458  123.50    0.0
4     2 -1.158233  0.877737  1.548718  ...  0.219422  0.215153   69.99    0.0

[5 rows x 31 columns]

In [ ]:
credit_card_data.tail()

         Time        V1        V2        V3  ...       V27       V28  Amount  Class
107041  70254 -2.953700  2.465992 -0.075277  ...  0.200626  0.145780    3.78    0.0
107042  70254 -1.284909  0.367581  1.381822  ... -0.238502 -0.276179  175.85    0.0
107043  70254  1.155595  0.262674  0.384212  ... -0.009953  0.019400    1.98    0.0
107044  70255  0.796110 -1.521441 -0.487824  ...  0.024517  0.066848  306.50    0.0
107045  70256  0.720550 -1.117795  0.069070  ...  0.102425       NaN     NaN    NaN

[5 rows x 31 columns]

In [ ]:
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 107046 entries, 0 to 107045
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    107046 non-null  int64
 1   V1      107046 non-null  float64
 2   V2      107046 non-null  float64
 3   V3      107046 non-null  float64
 4   V4      107046 non-null  float64
 5   V5      107046 non-null  float64
 6   V6      107046 non-null  float64
 7   V7      107046 non-null  float64
 8   V8      107046 non-null  float64
 9   V9      107046 non-null  float64
 10  V10     107046 non-null  float64
 11  V11     107046 non-null  float64
 12  V12     107046 non-null  float64
 13  V13     107046 non-null  float64
 14  V14     107046 non-null  float64
 15  V15     107046 non-null  float64
 16  V16     107046 non-null  float64
 17  V17     107046 non-null  float64
 18  V18     107046 non-null  float64
 19  V19     107046 non-null  float64
 20  V20     107046 non-null  float64
 21  V21     107046 non-null  float64
 22  V22     107046 non-null  float64
 23  V23     107046 non-null  float64
 24  V24     107046 non-null  float64
 25  V25     107046 non-null  float64
 26  V26     107046 non-null  float64
 27  V27     107046 non-null  float64
 28  V28     107045 non-null  float64
 29  Amount  107045 non-null  float64
 30  Class   107045 non-null  float64
dtypes: float64(30), int64(1)
memory usage: 25.3 MB

In [ ]:
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       1
Amount    1
Class     1
dtype: int64

In [ ]:

credit_card_data['Class'].value_counts()

Class
0.0    106810
1.0       235
Name: count, dtype: int64

In [ ]:
legit = credit_card_data[credit_card_data.Class==0]
fraud = credit_card_data[credit_card_data.Class==1]

In [ ]:
print(legit.shape)
print(fraud.shape)

(106810, 31)
(235, 31)

In [ ]:
legit.Amount.describe()

count    106810.000000
mean         96.160345
std         261.102076
min           0.000000
25%           7.110000
50%          25.190000
75%          86.970000
max       19656.530000
Name: Amount, dtype: float64

In [ ]:
fraud.Amount.describe()

count     235.000000
mean      115.033362
std       252.411933
min         0.000000
25%         1.000000
50%         7.580000
75%        99.990000
max      1809.680000
Name: Amount, dtype: float64

In [ ]:
credit_card_data.groupby('Class').mean()

               Time        V1        V2  ...       V27       V28      Amount
Class                                    ...
0.0    44175.833368 -0.245084 -0.035942  ...  0.000429  0.001501   96.160345
1.0    38307.157447 -6.055745  4.242095  ...  0.535474  0.064560  115.033362

[2 rows x 30 columns]

In [ ]:
for col in credit_card_data.columns:
    if credit_card_data[col].dtype != 'object':
        credit_card_data[col] = credit_card_data[col].fillna(credit_card_data[col].median())

In [ ]:
X= credit_card_data.drop(columns= 'Class', axis=1)

In [ ]:
Y = credit_card_data['Class']

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, stratify=Y, random_state=2)

In [ ]:
smote = SMOTE(random_state=1)

In [ ]:
X_train_res, Y_train_res = smote.fit_resample(X_train, Y_train)

In [ ]:
print(Y_train_res.shape)

(149536,)

In [ ]:
X_train.head()

        Time         V1        V2  ...       V27       V28  Amount
12270  21434 -10.453889  5.399837  ...  0.067433 -0.107398   89.99
61383  49806  -1.224176 -0.167151  ...  0.075399  0.040121   16.20
52077  45261  -2.973076  1.747776  ... -0.559434 -0.209954  193.97
95099  65169  -0.496016  0.155716  ... -0.063237 -0.108577   11.50
88071  61972  -2.121374 -1.460121  ... -0.027940  0.093600   69.23

[5 rows x 30 columns]

In [ ]:
print(X_train_res.shape)

(149536, 30)

In [ ]:
LORmodel = LogisticRegression(max_iter = 1000)

In [ ]:
LORmodel.fit(X_train_res,Y_train_res)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(max_iter=1000)

In [ ]:
X_train_prediction = LORmodel.predict(X_train_res)

In [ ]:
training_data_accuracy= accuracy_score(X_train_prediction, Y_train_res)

In [ ]:
print(training_data_accuracy)

0.97174593408945

In [ ]:
X_test_prediction = LORmodel.predict(X_test)

In [ ]:
print(accuracy_score(X_test_prediction, Y_test))

0.9872952606339914

In [ ]:
sample_data = (
    6644, 1.067611, 0.091006, -0.153917, 0.704233, 0.113894,
    -0.826866, 0.567690, -0.464181, 0.957295, -0.518488,
    0.443094, -1.829303, 2.852460, 1.701912, -0.037339,
    0.122023, 0.230354, -0.535946, 0.058243, 0.211006,
    -0.476723, -1.410090, -0.037550, -0.177773, 0.321810,
    0.114930, -0.109640, 0.023205, 139.90
)

In [ ]:
sample_data_numpy = np.asarray(sample_data)

In [ ]:
reshaped_sample_data = sample_data_numpy.reshape(1,-1)

In [ ]:
prediction = LORmodel.predict(reshaped_sample_data)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [ ]:
print(prediction)

[0.]

In [ ]:
print(classification_report(Y_test, X_test_prediction))

              precision    recall  f1-score   support

         0.0       1.00      0.99      0.99     32043
         1.0       0.14      0.94      0.25        71

    accuracy                           0.99     32114
   macro avg       0.57      0.97      0.62     32114
weighted avg       1.00      0.99      0.99     32114

In [ ]:
print(credit_card_data.shape)

(107046, 31)

In [ ]:
print(Y.value_counts())
print(Y_train.value_counts())
print(Y_test.value_counts())

Class
0.0    106811
1.0       235
Name: count, dtype: int64
Class
0.0    74768
1.0      164
Name: count, dtype: int64
Class
0.0    32043
1.0       71
Name: count, dtype: int64